### ISSUE TITLE
Link to a defined extension hook in Resource Timing & Nav Timing

### ISSUE THREAD

**Issue by igrigorik** [w3c/server-timing#19]
Currently we monkey patch ResourceTiming, which leaves a lot of ambiguity as to when exactly the steps needs to run. We should define a hook in RT and have ST call into it -- similar to how we have Page Visibility call into HTML rendering algorithm.

**Comment by cvazac** [comment]
Processing steps:
NT: https://www.w3.org/TR/navigation-timing-2/#processing-model
RT: https://www.w3.org/TR/resource-timing-2/#processing-model

**Comment by igrigorik** [comment]
Dupe of #38, let's continue there.
