### ISSUE TITLE
RT and NT processing is not well defined

### ISSUE THREAD

**Issue by igrigorik** [w3c/server-timing#38]
As a followup to https://github.com/w3c/server-timing/pull/36.

https://w3c.github.io/server-timing/#processing-model

> When processing the response of the current document, set the serverTiming attribute on the [newly created](https://www.w3.org/TR/navigation-timing-2/#step-create-object) PerformanceNavigationTiming object to the return value of the server-timing header parsing algorithm

You can't run the header parsing algorithm when the object is "newly created" because we don't yet have the response back from the server. 

> For each resource fetched by the current browsing context, excluding resources fetched by cross-origin stylesheets fetched with no-cors policy, set the serverTiming attribute on the newly created PerformanceResourceTiming object to:

- We shouldn't have to repeat the "excluding..." bits, that's already covered by ResourceTiming, which we're extending here.
- Similar to NT, the header parsing algorithm needs to run at the end, probably right before we "queue" the object at step 20 in RT.
   - We should define a formal hook in RT processing and call into that.

**Comment by siusin** [comment]
> Todd: Resource Timing 2 is the place to inject this hook, as it’s getting ready to ship. 
> ... Server timing just points to a linkable hook in Resource Timing 2.
> ...
> Yoav: Is there a specific example we can use as prior art for this text?

@cvazac the "steps to constrain a payment handler" processing model in the [payment method spec](https://s3.amazonaws.com/pr-preview/w3c/payment-method-basic-card/699e052...0e95c87.html) might be a good example --

> Optionally, set  card  ["  billingAddress  "] to the result running the steps to create a payment address

 (thanks @marcoscaceres )
