### ISSUE TITLE
Consider shorter names for the attributes

### ISSUE THREAD

**Issue by yoavweiss** [w3c/server-timing#40]
Feedback from the WebPerfWG TPAC F2F: shorter attribute names would mean smaller number of bytes on the wire. Let the bikeshed begin!!

**Comment by cvazac** [comment]
@achristensen07 do you have any feedback?

**Comment by achristensen07** [comment]
Ideally they would be one byte, like 't' for duration and 'd' for description.

**Comment by yoavweiss** [comment]
I think a single byte would significantly limit readability. The problem of fixed parameter names that are not well compressible seems to not be limited to server timing. [Link headers](https://tools.ietf.org/search/rfc5988) suffer from the same issue, and there are more recent examples that would equally suffer from it (e.g. Feature Policy).

Seems like something we should solve at the protocol level (as part of HPACK2 or QPACK ??)

/cc @mnot

**Comment by mnot** [comment]
If a header value is sent (as a whole) multiple times on the same connection, it'll fare well with HPACK. If not, it won't (beyond huffman encoding). This isn't likely to change, as there are security considerations involved (see: CRIME).

How often is this header going to be sent? Is it just in response headers? 

People generally overestimate the impact of header sizes on responses; compared to the response body, they're generally tiny. 

Without any more specific knowledge, `dur` and `desc` seem reasonable.

**Comment by cvazac** [comment]
fixed with https://github.com/w3c/server-timing/commit/1cf183e08407ada77da62e628422fea8ff45b64a
