### ISSUE TITLE
clarify invalid params

### ISSUE THREAD

**Issue by cvazac** [w3c/server-timing#48]
The processing algorithm needs to be clarified around invalid params. 

SPACE characters are not valid in tokens, so this is invalid:
```
metric; desc=d1 d2; dur=123
```

I think it's less controversial that we return a `description` of "d1". 

But when we detect that things aren't valid, should we try to continue parsing? Should `duration` become "123"? Or should we abort at that point we see the SPACE?

**Comment by colinbendell** [comment]
how are cookies processed?

**Comment by yoavweiss** [comment]
Since we’re not stopping parsing for other types of invalid values, I think the most consistent thing we can do here, is not to stop parsing here as well.

**Comment by cvazac** [comment]
We currently "keep going" in two instances:

1) For duplicate named params

> All subsequent occurrences MUST be ignored without signaling an error or otherwise altering the processing of the server-timing-metric.

2) When we can't convert a `dur` to a double

> Set duration to ... or value 0 if omitted or not representable as a double.

Here are some ramifications of "keep going":
```
metric=foo;dur=12,desc=d1
metric;dur=12 34;desc=d1
```
Both ^^^ yield "metric", 12, "d1", as "=" and " " (space) are not valid as tokens

```
metric1;desc=d1 d2,metric2
```
This ^^^ yields "metric1", "d1" AND "metric2"

**Comment by yoavweiss** [comment]
The above results make sense to me. The only reasonable and consistent alternative would have been to return no entry in any case of an error. It's not clear to me that the alternative is better, so we might as well continue on the path we started on.

**Comment by cvazac** [comment]
fixed with https://github.com/w3c/server-timing/pull/49
