### ISSUE TITLE
clarify extraneous characters after names

### ISSUE THREAD

**Issue by cvazac** [w3c/server-timing#51]
It is currently unspecified as to whether extraneous characters following `metric-name` should be ignored. 

We [ignore](https://github.com/w3c/server-timing/pull/49) extraneous characters found after a `server-timing-param-value`, so I'm inclined to do the same for `metric-name`s. 

Example:
```
Server-Timing: metric=;dur=123.4
```

Note: `=` is not a legal token character. 

Options:
1. parsing should "keep going", yielding:
name=metric
duration=123.4

2. parsing should stop, yielding:
name=metric
duration=0

cc @yoavweiss

**Comment by yoavweiss** [comment]
I think it makes sense for us to "keep going", drop parsing when a non-token-char is hit and skip till the next delimiter
