### ISSUE TITLE
Support in the Firefox DevTools?

### ISSUE THREAD

**Issue by SilentImp** [w3c/server-timing#64]
Hi,

Firefox declares full support of the Server-Timing API, but they don't actually show them in the DevTools network tab in distinction from Chrome and Safari.

It's only one of the use cases of Server-Timing, but maybe someone knows if there any plans and timings for that?

**Comment by igrigorik** [comment]
Please file a request / bug on https://bugzilla.mozilla.org/home. This repo is for the specification.. and, I'd love to see it surfaced in Moz devtools!

**Comment by SilentImp** [comment]
They actually already have it :(
https://bugzilla.mozilla.org/show_bug.cgi?id=1403051
no progress for half a year thru.

**Comment by beaufortfrancois** [comment]
It is now available in Firefox Nightly DevTools

![image](https://user-images.githubusercontent.com/634478/69800812-436b4b00-11d6-11ea-8ae2-051d85d34b48.png)
