### ISSUE TITLE
Creation time of PerformanceServerTiming objects unclear

### ISSUE THREAD

**Issue by annevk** [w3c/server-timing#69]
When exactly is this object created in relation to the event loop? In particular the trailer requirements seem inadequate, but everything else is quite vague as well.

**Comment by noamr** [comment]
https://github.com/w3c/server-timing/pull/87 fixed this.

**Comment by annevk** [comment]
I don't think so? This is specifically about when trailers are involved, which you hadn't tackled yet, right?

**Comment by noamr** [comment]
> I don't think so? This is specifically about when trailers are involved, which you hadn't tackled yet, right?

Right. Trailers are TBD pending implementor interest conversation. Leaving open
