### ISSUE TITLE
Exposing data on production

### ISSUE THREAD

**Issue by SilentImp** [w3c/server-timing#71]
Hi. 
I am trying to adopt this technology to make it easier to debug behaviour and to get additional data for RUM measurements and analysis.
But I face the situation when our DevOps team strongly against it because exposing stuff BAD, period. And if I want to collect any data I need to send it directly to the `prometheus`.
At that point, I expose timings for GraphQL requests at SSR of the react application. I don't see any way it may compromise the system, but maybe I miss something?
May you please share your point of view on that matter? 
Does it really put the project in danger?
What arguments may support my point of view?
Is it actually intended for production use?

With all best and kind regards. Anton.

**Comment by yoavweiss** [comment]
The severity of exposing data to the world varies wildly based on the nature of the data, so I'm afraid that without further analysis, it's hard to judge who is correct.

It may make sense in some cases to expose an obfuscated number to the world, which you can then internally translate to whatever data you're trying to capture.

Closing this, as this is not really an issue on the specification of the feature, but a general question.
