### ISSUE TITLE
Nested hierarchy and grouping of sub-tasks

### ISSUE THREAD

**Issue by ibnesayeed** [w3c/server-timing#78]
The spec seems not to suggest any structure in naming metrics, which makes the spec simple, but limits the ability of generalized client applications to visualize or report insights. It is desired to have a means to know the overall time of a step, but also the ability to investigate further at atomic sub-tasks level.

Are there any recommendations/conventions about how to include more structural information in names to encode parallel or sub-tasks? I have seen some examples in the wild using a dot-notation to reflect sub-tasks.

**Comment by noamr** [comment]
I think this is out of scope at the moment, closing. Feel free to reopen if ready to pursue this actively.
