### ISSUE TITLE
Server-Timing header field isn't registered

### ISSUE THREAD

**Issue by mnot** [w3c/server-timing#83]
See:
https://www.iana.org/assignments/message-headers/message-headers.xhtml

I see that the template is in the spec, but it appears that it hasn't actually been brought to IANA's attention.

**Comment by caribouW3** [comment]
Good catch.
I started the registration process as provisional header (since it's a WD), see
https://lists.w3.org/Archives/Public/public-web-perf/2021Oct/0000.html

**Comment by caribouW3** [comment]
The header field is now registered as a permanent header, see
https://www.iana.org/assignments/http-fields
